# Generated by Django 3.1.7 on 2021-02-27 07:45

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210215_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tovar', models.CharField(max_length=50)),
                ('price_tovar', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('image_tovar', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to='')),
                ('category_tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='rysar',
            name='soldat',
        ),
        migrations.RemoveField(
            model_name='soldat',
            name='rab',
        ),
        migrations.RemoveField(
            model_name='vazir',
            name='Sultan',
        ),
        migrations.RemoveField(
            model_name='vazir',
            name='rysar',
        ),
        migrations.DeleteModel(
            name='Rab',
        ),
        migrations.DeleteModel(
            name='Rysar',
        ),
        migrations.DeleteModel(
            name='Soldat',
        ),
        migrations.DeleteModel(
            name='Sultan',
        ),
        migrations.DeleteModel(
            name='Vazir',
        ),
    ]
