# Generated by Django 3.1.7 on 2021-02-28 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20210227_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('^\\d{1,5}$')], verbose_name='количество'),
        ),
    ]
